---
title       : matchmakr pitch
subtitle    : Dating reinvented
author      : Martin Kuhne
job         : Student, "Developing Data Products"
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Problem statement

- Dating sites suck
-- decisions are made behind the scenes on behalf of the user
-- high initial investment
-- can be expensive
- Tinder is too shallow
- Facebook is too scary

--- .class #id 

## Vision

Improve everyone's love life by providing a simple, self-contained, easy to use prediction for your relationship success

--- .class #id 

## Solution

- Provide a self-contained online solution
- Easy to use predicted conflict score for your romantic interest and yourself
- A quick, simple self assessment forms the basis for the assessment
- Done in under a minute
- Predicts a conflict score between 1 and 7, covering a span of "boring" to "disastrous"
- User can self-select desired level of harmony

We *categorically* deny the algorithm is implemented as
```{r eval=TRUE,echo=TRUE}
round(rnorm(1, mean=4), digits=0)
```

--- .class #id 

## Key takeaways

- It solves so many problems, conversion rate is going to be stellar!
- How many fallacies are in the slide deck? Discuss.
- This is what you get when you ask students to write any program of their choice 8-)
